owner: vp-en
repo: upptime
sites:
  - name: Plex Server
    url: $SECRET_SITE001
  - name: Bazarr
    url: $SECRET_SITE002
  - name: Bazarr4K
    url: $SECRET_SITE003
  - name: Chatbot
    url: $SECRET_SITE004
  - name: Dashdot
    url: $SECRET_SITE005
  - name: Gotify
    url: $SECRET_SITE006
  - name: Homepage (NSCBOX)
    url: $SECRET_SITE007
  - name: Komga
    url: $SECRET_SITE008
  - name: Lavalink
    url: $SECRET_SITE009
    expectedStatusCodes:
      - 401
  - name: MusicBot 01 (Carlos)
    url: $SECRET_SITE010
  - name: MusicBot 02 (RedArmy)
    url: $SECRET_SITE011
  - name: Mylar3
    url: $SECRET_SITE012
  - name: Notifiarr
    url: $SECRET_SITE013
  - name: Overseerr
    url: $SECRET_SITE014
  - name: Prowlarr
    url: $SECRET_SITE015
  - name: Pterodactyl Panel
    url: $SECRET_SITE016
  - name: Pterodactyl Node
    url: $SECRET_SITE017
    expectedStatusCodes:
      - 401
  - name: qBittorrent
    url: $SECRET_SITE018
  - name: Radarr
    url: $SECRET_SITE019
  - name: Radarr4K
    url: $SECRET_SITE020
  - name: SABnzbd
    url: $SECRET_SITE021
  - name: SABnzbd (Comics)
    url: $SECRET_SITE022
  - name: Sonarr
    url: $SECRET_SITE023
  - name: Sonarr4K
    url: $SECRET_SITE024
  - name: Tautulli
    url: $SECRET_SITE025
  - name: Whisparr
    url: $SECRET_SITE026
  - name: Wizarr
    url: $SECRET_SITE027
  - name: Wrapperr
    url: $SECRET_SITE028
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
status-website:
  cname: up.nscbox.eu
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime**"
  introMessage: Status page for NSCBOX
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
